# -*- coding: utf-8 -*-
"""DA_Assign_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/AbbunapuramVijay-1234/Data-Analytics/blob/main/DA_Assign_3.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/StudentsPerformance (1) (1) - StudentsPerformance (1) (1).csv')

df.info()

df.describe()

df.head(5)

df.shape

df.isnull().sum()

plt.boxplot(df['math score'], vert=False)

plt.boxplot(df['reading score'], vert=False)

plt.boxplot(df['writing score'], vert=False)

from sklearn.preprocessing import OneHotEncoder

categorical_cols = ['gender','race/ethnicity','parental level of education','lunch','test preparation course',]
encoder = OneHotEncoder(drop='first', sparse_output=False)
encoded_array = encoder.fit_transform(df[categorical_cols])
encoded_df = pd.DataFrame(encoded_array,columns=encoder.get_feature_names_out(categorical_cols),index=df.index,)
df_encoded = pd.concat([df.drop(columns=categorical_cols), encoded_df], axis=1)
df_encoded.head(10)

from sklearn.preprocessing import StandardScaler

numeric_cols = ['math score', 'reading score', 'writing score']

scaler = StandardScaler()

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

print(df[numeric_cols].head())

df.corr(numeric_only=True)

sns.heatmap(df.corr(numeric_only=True),cmap='coolwarm',annot=True)

sns.displot(df['math score'],bins=8)

sns.displot(df['reading score'],bins=8)

sns.displot(df['writing score'],bins=8)

score_cols = ['math score', 'reading score', 'writing score']
df['average_score'] = df[score_cols].mean(axis=1)
df['log_average_score'] = np.log1p(df['average_score'])
df[['average_score', 'log_average_score']].head()

